name: Trigger Logic App via Azure CLI

on:
  workflow_dispatch:

jobs:
  trigger-logicapp:
    runs-on: ubuntu-latest
    steps:

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Use a service principal with appropriate RBAC

      - name: Trigger Logic App
        run: |
          # Get the trigger callback URL for the Logic App
          callbackUrl=$(az logic workflow trigger callback-url show \
            --name MyLogicApp \
            --resource-group MyResourceGroup \
            --workflow-name manual \
            --query "value" -o tsv)

          echo "Triggering Logic App..."
          curl -X POST "$callbackUrl" \
            -H "Content-Type: application/json" \
            -d '{"source": "github", "status": "triggered"}'
