name: Upload PR Diff Files to Azure Blob Storage

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  upload-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get list of changed files
        id: diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Upload changed files to Azure Blob
        run: |
          while read -r file; do
            if [ -f "$file" ]; then
              echo "Uploading $file..."
              az storage blob upload \
                --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
                --container-name ${{ secrets.AZURE_CONTAINER_NAME }} \
                --name "$file" \
                --file "$file" \
                --auth-mode login \
                --overwrite
            fi
          done < changed_files.txt
